[tool.poetry]
name = "jump_rr"
version = "0.1.0"
description = "Tools to compare profiles in a round-robin manner (all-vs-all)"
authors = ["Alan"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
broad-babel = "^0.1.11"
copairs = {git = "https://github.com/cytomining/copairs.git", rev = "v0.4.0-alpha"}
numpy = "*"
fastcluster = "^1.2.6"
pyarrow = "^14.0.1"
joblib = "^1.3.2"
adbc-driver-sqlite = "^0.8.0"
polars = "*"
cudf-cu11 = {version = "==23.12.*", source = "nvidia"}
pylibraft-cu11 = {version = "==23.12.*", source = "nvidia"}
raft-dask-cu11 = {version = "==23.12.*", source = "nvidia"}
rmm-cu11 = {version = "^23.12.0", source = "nvidia"}
ucx-py-cu11 = {version = "^0.35.0", source = "nvidia"}
ptxcompiler-cu11 = {version = "^0.7.0.post1", source = "nvidia"}
cubinlinker-cu11 = {version = "^0.3.0.post1", source = "nvidia"}
anndata = "^0.10.5.post1"
pandas = "<1.6.0dev0"
seaborn = "^0.13.2"
scikit-learn = "^1.4.0"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
jupytext = "^1.15.2"
ipdb = "^0.13.13"
ruff-lsp = "^0.0.50"
jupyter-black = "^0.3.4"


[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
priority = "explicit"


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
